services:
  # envoy:
  #   image: envoyproxy/envoy:v1.31-latest
  #   ports:
  #     - "8080:8080"
  #     - "9901:9901"
  #   volumes:
  #     - ./envoy.yaml:/etc/envoy/envoy.yaml
  #   depends_on:
  #     - document_service

  # document_service:
  #   build:
  #     context: .
  #     dockerfile: dockerfile.documentservice
  #   expose:
  #     - "50005"
  redis:
    image: redis:latest
    restart: always
    volumes:
      - cache:/tmp/docker.redis.data
    ports:
      - "6379:6379"

volumes:
  cache:
    driver: local
